kind: pipeline
type: docker
name: default

steps:

- name: probely
  image: bbarao/drone-test
  environment:
    PLUGIN_API_KEY:
      from_secret: p_api_key
    PLUGIN_TARGET_ID:
      from_secret: p_target_id
    PLUGIN_REGION:
      from_secret: p_region
    PLUGIN_SCAN_PROFILE:
      from_secret: p_scan_profile
